### ISSUE TITLE
Deleting throws exception when using KMS alias

### ISSUE THREAD

**Issue by basschipper** [binxio/cfn-kms-provider#1]
When using a KMS alias instead of a KMS id a exception is thrown during deletions:
```
Failed to delete resource. Parameter validation failed: Invalid type for parameter KeyId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

I think because the KeyId at the following line is not available:
https://github.com/binxio/cfn-kms-provider/blob/master/src/cfn_kms_provider.py#L90

**Comment by basschipper** [comment]
Besides the issue above, I also have a question. This resource is being deployed in the target account, right? So the account that uses the CMK?

How can this target account with a `list_aliases` find the corresponding alias in the source account at all? This is a cross account action, isn't it?

Or am I missing something here?

**Comment by mvanholsteijn** [comment]
The alias will not work as you cannot list aliases across account.  
I use [Custom::AMI](https://github.com/binxio/cfn-ami-provider/blob/master/docs/AMI.md) to obtain the key with which the image was encrypted.

**Comment by mvanholsteijn** [comment]
Anyway, it is fixed in version 0.1.4;

**Comment by basschipper** [comment]
Thanks! 

Just had a look at he Custom::AMI, but that presumes the AMI already exists before the Landing Zone deployes the KMS grant? So:
1. LZ deployes CMK
2. Encrypted AMI is produced
3. LZ deployes KMS grant.
Not sure if I like that.

BTW, I really love the effort you guys put in all these custom resources, keep up the good work!

**Comment by mvanholsteijn** [comment]
I do not know your use case, for us the grant was required to start AMIs in
a ASG. This requires that you have the AMI anyway. The problem with
pre-provisioning the grant comes when your key changes. as there is no
trigger that will update your custom provider. This will leave you with a
broken system as the grant is referring to the wrong key.

>
>
